### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by phenometry** [fdraxler/PyTorch-AutoNEB#5]
Dear all,

I am new to python and I was interested to try AutoNEB.
I installed the prerequisites successfully as mentioned. 
(python 3.8.3 and numpy 1.20.3)
I tried python main.py project_directory config_file
and I get thee below;

 File "main.py", line 131, in <module>
    main()
  File "main.py", line 68, in main
    graph_path, project_config_path = setup_project(config_file, project_directory)
  File "main.py", line 105, in setup_project
    raise ValueError(f"Config file {config_file} not found.")
ValueError: Config file config_file not found.

How can I fix this ?
Thank you

**Comment by fdraxler** [comment]
Hi, thank you for your question. You will need to call the script like this:
`python <PROJECT_DIRECTORY> <CONFIG_FILE>`

Here, `PROJECT_DIRECTORY` is the path to a folder where results should be stored, and `CONFIG_FILE` is the path to an existing configuration file which you can find in the [configs folder](https://github.com/fdraxler/PyTorch-AutoNEB/tree/master/configs).

**Comment by fdraxler** [comment]
Beware that this library has not been updated for three years now, so I cannot guarantee that the code is compatible to the newer versions of libraries like PyTorch.

**Comment by phenometry** [comment]
thank you for your response.

**Comment by phenometry** [comment]
Thanks to your response, I paid more attention to the instructions, 
I chose one of the .yaml(s) in the config directory. 
So I did:
 python main.py ..  C:\Users\conta\PyTorch-AutoNEB\configs\cifar10-cnn12.yaml

and I got the below: 

Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to C:\Users\conta\PyTorch-AutoNEB\tmp\cifar10\cifar-10-python.tar.gz
100%|█████████████████████████████████████████████████████████████▉| 170229760/170498071 [00:24<00:00, 16478417.28it/s]Extracting C:\Users\conta\PyTorch-AutoNEB\tmp\cifar10\cifar-10-python.tar.gz to C:\Users\conta\PyTorch-AutoNEB\tmp\cifar10
Files already downloaded and verified
Traceback (most recent call last):
  File "main.py", line 131, in <module>
    main()
  File "main.py", line 70, in main
    model, minima_count, min_config, lex_config = read_config_file(project_config_path)
  File "main.py", line 32, in read_config_file
    model = architecture(**arguments)
  File "C:\Users\conta\PyTorch-AutoNEB\torch_autoneb\models\cnn.py", line 40, in __init__
    dims /= Tensor(pool_size).to(int64)
RuntimeError: result type Float can't be cast to the desired output type Long
170500096it [00:28, 5918821.23it/s]

There is a torch runtimeerror which I have to resolve.
